=== lheo/lheo-schema/definition/tmp/gml.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT definitions (definition*, dict*, property*)>

<!ATTLIST definitions 
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xmlns:pgml CDATA #FIXED "http://www.gelaba.org/pgml"
	  language CDATA #REQUIRED
	  namespace CDATA #REQUIRED 
	  default_root CDATA #IMPLIED
	  xml:lang CDATA #REQUIRED>

<!ELEMENT definition (fullname*, doc*, element_type, attribute*, property*)>

<!ATTLIST definition 
	  name ID #REQUIRED>

<!ELEMENT element_type (sequence | choice | empty | basic_int | basic_float | basic_date | basic_text | basic_name | basic_key | basic_data)>

<!ELEMENT sequence (element+)>

<!ELEMENT element (doc*)>

<!ATTLIST element 
	  name IDREF #REQUIRED 
	  min CDATA "1" 
	  max CDATA "1">

<!ELEMENT choice (choice_element+)>

<!ATTLIST choice
	  min CDATA "1" 
	  max CDATA "1">

<!ELEMENT choice_element (doc*)>

<!ATTLIST choice_element name IDREF #REQUIRED>

<!ELEMENT empty EMPTY>

<!ELEMENT basic_int (doc*, property*, example*)>

<!ATTLIST basic_int 
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_float (doc*, property*, example*)>

<!ATTLIST basic_float
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_date (doc*, property*, example*)>

<!ATTLIST basic_date
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_text (doc*, property*)>

<!ATTLIST basic_text
	  lgmin CDATA "0"
	  lgmax CDATA "0" 
	  regexp CDATA #IMPLIED>

<!ELEMENT basic_name (doc*, property*)>

<!ATTLIST basic_name
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT basic_key (doc*, property*)>

<!ATTLIST basic_key
	  ref IDREF #REQUIRED>

<!ELEMENT basic_data (doc*, property*)>

<!ELEMENT attribute (fullname*,doc*,attribute_type,property*)>

<!ATTLIST attribute 
	  name NMTOKEN #REQUIRED
	  type (default|fixed|optional|required) #REQUIRED
	  value CDATA #IMPLIED>

<!ELEMENT attribute_type (attribute_int | attribute_float | attribute_date | attribute_text | attribute_name | attribute_key | attribute_embedded_key | attribute_id | attribute_idref)>

<!ELEMENT attribute_int (doc*, property*)>

<!ATTLIST attribute_int 
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_float (doc*, property*)>

<!ATTLIST attribute_float
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_date (doc*, property*)>

<!ATTLIST attribute_date
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_text (doc*, property*)>

<!ATTLIST attribute_text
	  lgmin CDATA "0"
	  lgmax CDATA "0" 
	  regexp CDATA #IMPLIED>

<!ELEMENT attribute_name (doc*, property*)>

<!ATTLIST attribute_name
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_key (doc*, property*)>

<!ATTLIST attribute_key
	  ref IDREF #REQUIRED>

<!ELEMENT attribute_embedded_key (doc*, property*)>

<!ATTLIST attribute_embedded_key
	  ref IDREF #REQUIRED>

<!ELEMENT attribute_id (doc*, property*)>

<!ATTLIST attribute_id
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_idref (doc*, property*)>

<!ATTLIST attribute_idref
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT fullname (#PCDATA)>

<!ATTLIST fullname 
	  xml:lang CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>

<!ATTLIST doc 
	  xml:lang CDATA #REQUIRED>

<!ELEMENT property (doc*,data?)>

<!ATTLIST property 
	  name CDATA #REQUIRED 
	  value CDATA #IMPLIED>

<!ELEMENT data (#PCDATA)>

<!ELEMENT dict (fullname*, doc*, entry*, property*)>

<!ATTLIST dict
	  name ID #REQUIRED>

<!ELEMENT entry (key+, value*, doc*, property*)>

<!ELEMENT key EMPTY>

<!ATTLIST key 
	  val CDATA #REQUIRED>

<!ELEMENT value (data?)>

<!ATTLIST value 
	  xml:lang CDATA #IMPLIED 
	  val CDATA #REQUIRED>

<!ELEMENT dictionaries (dict*)>
<!ATTLIST dictionaries 
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xml:lang CDATA #REQUIRED>

<!ELEMENT properties (property*)>
<!ATTLIST properties 
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xml:lang CDATA #REQUIRED>

<!ELEMENT attributes (attribute*)>
<!ATTLIST attributes
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xml:lang CDATA #REQUIRED>

<!ELEMENT examples (example*)>
<!ATTLIST examples
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xml:lang CDATA #REQUIRED>

<!ELEMENT example (doc*,example_content?,example_attribute*,property*)>
<!ATTLIST example
	  name NMTOKEN #REQUIRED
	  valid (yes|no) #REQUIRED>

<!ELEMENT example_content (#PCDATA)>

<!ELEMENT example_attribute EMPTY>
<!ATTLIST example_attribute
	  name NMTOKEN #REQUIRED
	  value CDATA #REQUIRED>

=== lheo/lheo-schema/definition/tmp/dict-regions-france.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.0" name="dict-regions-france">
  <fullname xml:lang="fr">Régions françaises</fullname>
  <entry>
    <key val="01"/>
    <key val="1"/>
    <value xml:lang="fr" val="Guadeloupe"/>
  </entry>
  <entry>
    <key val="02"/>
    <key val="2"/>
    <value xml:lang="fr" val="Martinique"/>
  </entry>
  <entry>
    <key val="03"/>
    <key val="3"/>
    <value xml:lang="fr" val="Guyane"/>
  </entry>
  <entry>
    <key val="04"/>
    <key val="4"/>
    <value xml:lang="fr" val="Réunion"/>
  </entry>
  <entry>
    <key val="11"/>
    <value xml:lang="fr" val="Île-de-France"/>
  </entry>
  <entry>
    <key val="21"/>
    <value xml:lang="fr" val="Champagne-Ardenne"/>
  </entry>
  <entry>
    <key val="22"/>
    <value xml:lang="fr" val="Picardie"/>
  </entry>
  <entry>
    <key val="23"/>
    <value xml:lang="fr" val="Haute-Normandie"/>
  </entry>
  <entry>
    <key val="24"/>
    <value xml:lang="fr" val="Centre"/>
  </entry>
  <entry>
    <key val="25"/>
    <value xml:lang="fr" val="Basse-Normandie"/>
  </entry>
  <entry>
    <key val="26"/>
    <value xml:lang="fr" val="Bourgogne"/>
  </entry>
  <entry>
    <key val="31"/>
    <value xml:lang="fr" val="Nord-Pas-de-Calais"/>
  </entry>
  <entry>
    <key val="41"/>
    <value xml:lang="fr" val="Lorraine"/>
  </entry>
  <entry>
    <key val="42"/>
    <value xml:lang="fr" val="Alsace"/>
  </entry>
  <entry>
    <key val="43"/>
    <value xml:lang="fr" val="Franche-Comté"/>
  </entry>
  <entry>
    <key val="52"/>
    <value xml:lang="fr" val="Pays de la Loire"/>
  </entry>
  <entry>
    <key val="53"/>
    <value xml:lang="fr" val="Bretagne"/>
  </entry>
  <entry>
    <key val="54"/>
    <value xml:lang="fr" val="Poitou-Charentes"/>
  </entry>
  <entry>
    <key val="72"/>
    <value xml:lang="fr" val="Aquitaine"/>
  </entry>
  <entry>
    <key val="73"/>
    <value xml:lang="fr" val="Midi-Pyrénées"/>
  </entry>
  <entry>
    <key val="74"/>
    <value xml:lang="fr" val="Limousin"/>
  </entry>
  <entry>
    <key val="82"/>
    <value xml:lang="fr" val="Rhône-Alpes"/>
  </entry>
  <entry>
    <key val="83"/>
    <value xml:lang="fr" val="Auvergne"/>
  </entry>
  <entry>
    <key val="91"/>
    <value xml:lang="fr" val="Languedoc-Roussillon"/>
  </entry>
  <entry>
    <key val="93"/>
    <value xml:lang="fr" val="Provence-Alpes-Côte d'Azur"/>
  </entry>
  <entry>
    <key val="94"/>
    <value xml:lang="fr" val="Corse"/>
  </entry>
</dict>
