=== lheo/lheo-schema/definition/atraiter/gml.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
	NOTE: this DTD has attributes with default values.
	The generated DTD from the GML definition has not.
	The implementation of tools using GML definitions should
	not assume that the DTD is present and then, those values
	are just defined for convenience. The normative version of the
	GML definition is 'gml.xml'.

	TODO: add a flag in "date" content to specify whether the date
	should be a real one or not.

	TODO: add an attribute to each key: @namespace to identify the namespace
	of the dictionary.

	TODO: int is 64 bits (long long in C99, long in Java).

	TODO: float is 64 bits (double in C99, double in Java).

	TODO: for TEXT, NAME, ID, IDREF, max size is limited to
	INT_MAX (32 bits). This should be used as a default value.
-->
<!ELEMENT definitions (namespace*, definition*, dict*, property*)>

<!ATTLIST definitions 
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xmlns:pgml CDATA #FIXED "http://www.gelaba.org/pgml"
	  language CDATA #REQUIRED
	  prefix CDATA #REQUIRED
	  version CDATA #IMPLIED 
	  default_root CDATA #IMPLIED
	  xml:lang CDATA "en">

<!ELEMENT namespace (fullname*, doc*)>
<!ATTLIST namespace
	  prefix CDATA #REQUIRED
	  href CDATA #REQUIRED>

<!ELEMENT definition (fullname*, doc*, element_type, attribute*, property*)>

<!ATTLIST definition 
	  name NMTOKEN #REQUIRED
	  namespace CDATA #IMPLIED>

<!ELEMENT element_type (sequence | choice | empty | basic_int | basic_float | basic_date | basic_text | basic_name | basic_key | basic_data)>

<!ELEMENT sequence (element+)>

<!ELEMENT element (doc*)>

<!ATTLIST element 
	  name NMTOKEN #REQUIRED 
	  min CDATA "1" 
	  max CDATA "1"
	  namespace CDATA #IMPLIED>

<!ELEMENT choice (choice_element+)>

<!ATTLIST choice
	  min CDATA "1" 
	  max CDATA "1">

<!ELEMENT choice_element (doc*)>

<!ATTLIST choice_element 
	  name NMTOKEN #REQUIRED
	  namespace CDATA #IMPLIED>

<!ELEMENT empty EMPTY>

<!ELEMENT basic_int (doc*)>

<!ATTLIST basic_int 
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_float (doc*)>

<!ATTLIST basic_float
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_date (doc*)>

<!ATTLIST basic_date
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_text (doc*)>

<!ATTLIST basic_text
	  lgmin CDATA "0"
	  lgmax CDATA "0" 
	  regexp CDATA #IMPLIED>

<!ELEMENT basic_name (doc*)>

<!ATTLIST basic_name
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT basic_key (doc*)>

<!ATTLIST basic_key
	  ref NMTOKEN #REQUIRED>

<!ELEMENT basic_data (doc*)>

<!ELEMENT attribute (fullname*,doc*,attribute_type,property*)>

<!ATTLIST attribute 
	  name NMTOKEN #REQUIRED
	  type (default|fixed|optional|required) #REQUIRED
	  value CDATA #IMPLIED>

<!ELEMENT attribute_type (attribute_int | attribute_float | attribute_date | attribute_text | attribute_name | attribute_key | attribute_embedded_key | attribute_id | attribute_idref | attribute_data)>

<!ELEMENT attribute_int (doc*)>

<!ATTLIST attribute_int 
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_float (doc*)>

<!ATTLIST attribute_float
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_date (doc*)>

<!ATTLIST attribute_date
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_text (doc*)>

<!ATTLIST attribute_text
	  lgmin CDATA "0"
	  lgmax CDATA "0" 
	  regexp CDATA #IMPLIED>

<!ELEMENT attribute_name (doc*)>

<!ATTLIST attribute_name
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_key (doc*)>

<!ATTLIST attribute_key
	  ref NMTOKEN #REQUIRED>

<!ELEMENT attribute_embedded_key (doc*)>

<!ATTLIST attribute_embedded_key
	  ref NMTOKEN #REQUIRED>

<!ELEMENT attribute_id (doc*)>

<!ATTLIST attribute_id
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_idref (doc*)>

<!ATTLIST attribute_idref
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_data (doc*)>

<!ELEMENT fullname (#PCDATA)>

<!ATTLIST fullname 
	  xml:lang CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>

<!ATTLIST doc 
	  xml:lang CDATA #REQUIRED>

<!ELEMENT property (doc*,data?)>

<!ATTLIST property 
	  name CDATA #REQUIRED 
	  value CDATA #IMPLIED>

<!ELEMENT data (#PCDATA)>

<!ELEMENT dict (fullname*, doc*, entry*, property*)>

<!ATTLIST dict
	  name NMTOKEN #REQUIRED
	  namespace CDATA #IMPLIED>

<!ELEMENT entry (key+, value*, doc*)>

<!ELEMENT key EMPTY>

<!ATTLIST key 
	  val CDATA #REQUIRED>

<!ELEMENT value (data?)>

<!ATTLIST value 
	  xml:lang CDATA #IMPLIED 
	  val CDATA #REQUIRED>

<!ELEMENT examples (example*)>
<!ATTLIST examples
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xml:lang CDATA #REQUIRED>

<!ELEMENT example (doc*,example_content?,example_attribute*)>
<!ATTLIST example
	  name NMTOKEN #REQUIRED
	  valid (yes|no) #REQUIRED>

<!ELEMENT example_content (#PCDATA)>

<!ELEMENT example_attribute EMPTY>
<!ATTLIST example_attribute
	  name NMTOKEN #REQUIRED
	  value CDATA #REQUIRED>

=== lheo/lheo-schema/definition/dict-financeurs-formacodes-V10.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-financeurs-formacodes-V10">
  <fullname xml:lang="fr">Financeurs formacodes V10</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="98012" />
      <value xml:lang="fr" val="ACSE" />
    </entry>
    <entry>
      <key val="98014" />
      <value xml:lang="fr" val="AFPA" />
    </entry>
    <entry>
      <key val="98011" />
      <value xml:lang="fr" val="AGEFIPH" />
    </entry>
    <entry>
      <key val="98019" />
      <value xml:lang="fr" val="Bénéficiaire action" />
    </entry>
    <entry>
      <key val="98006" />
      <value xml:lang="fr" val="Collectivité territoriale-autre" />
    </entry>
    <entry>
      <key val="98008" />
      <value xml:lang="fr" val="Collectivité territoriale-commune" />
    </entry>
    <entry>
      <key val="98009" />
      <value xml:lang="fr" val="Collectivité territoriale-conseil général" />
    </entry>
    <entry>
      <key val="98005" />
      <value xml:lang="fr" val="Collectivité territoriale-conseil régional" />
    </entry>
    <entry>
      <key val="98020" />
      <value xml:lang="fr" val="Entreprise" />
    </entry>
    <entry>
      <key val="98004" />
      <value xml:lang="fr" val="Etat-autre" />
    </entry>
    <entry>
      <key val="98040" />
      <value xml:lang="fr" val="Etat-ministère autre" />
    </entry>
    <entry>
      <key val="98015" />
      <value xml:lang="fr" val="Etat-ministère chargé de l'emploi" />
    </entry>
    <entry>
      <key val="98010" />
      <value xml:lang="fr" val="Financement européen-autre" />
    </entry>
    <entry>
      <key val="98037" />
      <value xml:lang="fr" val="Financement européen-FSE" />
    </entry>
    <entry>
      <key val="98017" />
      <value xml:lang="fr" val="OPACIF" />
    </entry>
    <entry>
      <key val="98018" />
      <value xml:lang="fr" val="OPCA" />
    </entry>
    <entry>
      <key val="98013" />
      <value xml:lang="fr" val="Pôle emploi" />
    </entry>
    <entry>
      <key val="98007" />
      <value xml:lang="fr" val="UNEDIC" />
    </entry>
  <property name="version" value="V10" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/dict-perimetre-recrutement.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-perimetre-recrutement">
  <fullname xml:lang="fr">Périmètre de recrutement</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="0"/>
      <value xml:lang="fr" val="Autres"/>
    </entry>
    <entry>
      <key val="1"/>
      <value xml:lang="fr" val="Commune"/>
    </entry>
    <entry>
      <key val="2"/>
      <value xml:lang="fr" val="Département"/>
    </entry>
    <entry>
      <key val="3"/>
      <value xml:lang="fr" val="Région"/>
    </entry>
    <entry>
      <key val="4"/>
      <value xml:lang="fr" val="Interrégion"/>
    </entry>
    <entry>
      <key val="5"/>
      <value xml:lang="fr" val="Pays"/>
    </entry>
    <entry>
      <key val="6"/>
      <value xml:lang="fr" val="International"/>
    </entry>
  <property name="version" value="V1" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/sources/lheo-dict-regions-france.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-regions-france">
<fullname xml:lang="fr">Régions françaises (2007)</fullname>
<doc xml:lang="fr">Régions françaises version 2007 (source: INSEE).</doc>
<entry>
  <key val="01" />
  <value xml:lang="fr" val="Guadeloupe" />
  <property name="insee:cheflieu" value="97105" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="02" />
  <value xml:lang="fr" val="Martinique" />
  <property name="insee:cheflieu" value="97209" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="03" />
  <value xml:lang="fr" val="Guyane" />
  <property name="insee:cheflieu" value="97302" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="04" />
  <value xml:lang="fr" val="La Réunion" />
  <property name="insee:cheflieu" value="97411" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="11" />
  <value xml:lang="fr" val="Île-de-France" />
  <property name="insee:cheflieu" value="75056" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="21" />
  <value xml:lang="fr" val="Champagne-Ardenne" />
  <property name="insee:cheflieu" value="51108" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="22" />
  <value xml:lang="fr" val="Picardie" />
  <property name="insee:cheflieu" value="80021" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="23" />
  <value xml:lang="fr" val="Haute-Normandie" />
  <property name="insee:cheflieu" value="76540" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="24" />
  <value xml:lang="fr" val="Centre" />
  <property name="insee:cheflieu" value="45234" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="25" />
  <value xml:lang="fr" val="Basse-Normandie" />
  <property name="insee:cheflieu" value="14118" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="26" />
  <value xml:lang="fr" val="Bourgogne" />
  <property name="insee:cheflieu" value="21231" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="31" />
  <value xml:lang="fr" val="Nord-Pas-de-Calais" />
  <property name="insee:cheflieu" value="59350" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="41" />
  <value xml:lang="fr" val="Lorraine" />
  <property name="insee:cheflieu" value="57463" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="42" />
  <value xml:lang="fr" val="Alsace" />
  <property name="insee:cheflieu" value="67482" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="43" />
  <value xml:lang="fr" val="Franche-Comté" />
  <property name="insee:cheflieu" value="25056" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="52" />
  <value xml:lang="fr" val="Pays de la Loire" />
  <property name="insee:cheflieu" value="44109" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="53" />
  <value xml:lang="fr" val="Bretagne" />
  <property name="insee:cheflieu" value="35238" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="54" />
  <value xml:lang="fr" val="Poitou-Charentes" />
  <property name="insee:cheflieu" value="86194" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="72" />
  <value xml:lang="fr" val="Aquitaine" />
  <property name="insee:cheflieu" value="33063" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="73" />
  <value xml:lang="fr" val="Midi-Pyrénées" />
  <property name="insee:cheflieu" value="31555" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="74" />
  <value xml:lang="fr" val="Limousin" />
  <property name="insee:cheflieu" value="87085" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="82" />
  <value xml:lang="fr" val="Rhône-Alpes" />
  <property name="insee:cheflieu" value="69123" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="83" />
  <value xml:lang="fr" val="Auvergne" />
  <property name="insee:cheflieu" value="63113" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="91" />
  <value xml:lang="fr" val="Languedoc-Roussillon" />
  <property name="insee:cheflieu" value="34172" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="93" />
  <value xml:lang="fr" val="Provence-Alpes-Côte d'Azur" />
  <property name="insee:cheflieu" value="13055" />
  <property name="iso:pays" value="FR" />
</entry>
<entry>
  <key val="94" />
  <value xml:lang="fr" val="Corse" />
  <property name="insee:cheflieu" value="2A004" />
  <property name="iso:pays" value="FR" />
</entry>
<property name="version" value="2007" />
<property name="wikipedia" value="http://fr.wikipedia.org/wiki/Région_française" />
<property name="url" value="http://www.insee.fr/fr/nom_def_met/nomenclatures/cog/cog.telechargement.asp" />
</dict>
