=== lheo/lheo-schema/definition/atraiter/gml.dtd
<?xml version="1.0" encoding="utf-8"?>
<!--
	NOTE: this DTD has attributes with default values.
	The generated DTD from the GML definition has not.
	The implementation of tools using GML definitions should
	not assume that the DTD is present and then, those values
	are just defined for convenience. The normative version of the
	GML definition is 'gml.xml'.

	TODO: add a flag in "date" content to specify whether the date
	should be a real one or not.

	TODO: add an attribute to each key: @namespace to identify the namespace
	of the dictionary.

	TODO: int is 64 bits (long long in C99, long in Java).

	TODO: float is 64 bits (double in C99, double in Java).

	TODO: for TEXT, NAME, ID, IDREF, max size is limited to
	INT_MAX (32 bits). This should be used as a default value.
-->
<!ELEMENT definitions (namespace*, definition*, dict*, property*)>

<!ATTLIST definitions 
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xmlns:pgml CDATA #FIXED "http://www.gelaba.org/pgml"
	  language CDATA #REQUIRED
	  prefix CDATA #REQUIRED
	  version CDATA #IMPLIED 
	  default_root CDATA #IMPLIED
	  xml:lang CDATA "en">

<!ELEMENT namespace (fullname*, doc*)>
<!ATTLIST namespace
	  prefix CDATA #REQUIRED
	  href CDATA #REQUIRED>

<!ELEMENT definition (fullname*, doc*, element_type, attribute*, property*)>

<!ATTLIST definition 
	  name NMTOKEN #REQUIRED
	  namespace CDATA #IMPLIED>

<!ELEMENT element_type (sequence | choice | empty | basic_int | basic_float | basic_date | basic_text | basic_name | basic_key | basic_data)>

<!ELEMENT sequence (element+)>

<!ELEMENT element (doc*)>

<!ATTLIST element 
	  name NMTOKEN #REQUIRED 
	  min CDATA "1" 
	  max CDATA "1"
	  namespace CDATA #IMPLIED>

<!ELEMENT choice (choice_element+)>

<!ATTLIST choice
	  min CDATA "1" 
	  max CDATA "1">

<!ELEMENT choice_element (doc*)>

<!ATTLIST choice_element 
	  name NMTOKEN #REQUIRED
	  namespace CDATA #IMPLIED>

<!ELEMENT empty EMPTY>

<!ELEMENT basic_int (doc*)>

<!ATTLIST basic_int 
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_float (doc*)>

<!ATTLIST basic_float
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_date (doc*)>

<!ATTLIST basic_date
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT basic_text (doc*)>

<!ATTLIST basic_text
	  lgmin CDATA "0"
	  lgmax CDATA "0" 
	  regexp CDATA #IMPLIED>

<!ELEMENT basic_name (doc*)>

<!ATTLIST basic_name
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT basic_key (doc*)>

<!ATTLIST basic_key
	  ref NMTOKEN #REQUIRED>

<!ELEMENT basic_data (doc*)>

<!ELEMENT attribute (fullname*,doc*,attribute_type,property*)>

<!ATTLIST attribute 
	  name NMTOKEN #REQUIRED
	  type (default|fixed|optional|required) #REQUIRED
	  value CDATA #IMPLIED>

<!ELEMENT attribute_type (attribute_int | attribute_float | attribute_date | attribute_text | attribute_name | attribute_key | attribute_embedded_key | attribute_id | attribute_idref | attribute_data)>

<!ELEMENT attribute_int (doc*)>

<!ATTLIST attribute_int 
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_float (doc*)>

<!ATTLIST attribute_float
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_date (doc*)>

<!ATTLIST attribute_date
	  vmin CDATA #IMPLIED 
	  vmax CDATA #IMPLIED>

<!ELEMENT attribute_text (doc*)>

<!ATTLIST attribute_text
	  lgmin CDATA "0"
	  lgmax CDATA "0" 
	  regexp CDATA #IMPLIED>

<!ELEMENT attribute_name (doc*)>

<!ATTLIST attribute_name
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_key (doc*)>

<!ATTLIST attribute_key
	  ref NMTOKEN #REQUIRED>

<!ELEMENT attribute_embedded_key (doc*)>

<!ATTLIST attribute_embedded_key
	  ref NMTOKEN #REQUIRED>

<!ELEMENT attribute_id (doc*)>

<!ATTLIST attribute_id
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_idref (doc*)>

<!ATTLIST attribute_idref
	  lgmin CDATA "0"
	  lgmax CDATA "0">

<!ELEMENT attribute_data (doc*)>

<!ELEMENT fullname (#PCDATA)>

<!ATTLIST fullname 
	  xml:lang CDATA #REQUIRED>

<!ELEMENT doc (#PCDATA)>

<!ATTLIST doc 
	  xml:lang CDATA #REQUIRED>

<!ELEMENT property (doc*,data?)>

<!ATTLIST property 
	  name CDATA #REQUIRED 
	  value CDATA #IMPLIED>

<!ELEMENT data (#PCDATA)>

<!ELEMENT dict (fullname*, doc*, entry*, property*)>

<!ATTLIST dict
	  name NMTOKEN #REQUIRED
	  namespace CDATA #IMPLIED>

<!ELEMENT entry (key+, value*, doc*)>

<!ELEMENT key EMPTY>

<!ATTLIST key 
	  val CDATA #REQUIRED>

<!ELEMENT value (data?)>

<!ATTLIST value 
	  xml:lang CDATA #IMPLIED 
	  val CDATA #REQUIRED>

<!ELEMENT examples (example*)>
<!ATTLIST examples
	  xmlns CDATA #FIXED "http://www.gelaba.org/gml/1.0"
	  xml:lang CDATA #REQUIRED>

<!ELEMENT example (doc*,example_content?,example_attribute*)>
<!ATTLIST example
	  name NMTOKEN #REQUIRED
	  valid (yes|no) #REQUIRED>

<!ELEMENT example_content (#PCDATA)>

<!ELEMENT example_attribute EMPTY>
<!ATTLIST example_attribute
	  name NMTOKEN #REQUIRED
	  value CDATA #REQUIRED>

=== lheo/lheo-schema/definition/dict-modalites-pedagogiques-formacodes-V10.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-modalites-pedagogiques-formacodes-V10">
  <fullname xml:lang="fr">Modalités pédagogiques formacodes V10</fullname>
  <doc xml:lang="fr">
  </doc>
   <entry>
      <key val="96121" />
      <value xml:lang="fr" val="Modalités pédagogiques" />
    </entry>
    <entry>
      <key val="96124" />
      <value xml:lang="fr" val="Autoformation" />
    </entry>
    <entry>
      <key val="96125" />
      <value xml:lang="fr" val="Autoformation avec tutorat" />
    </entry>
    <entry>
      <key val="96126" />
      <value xml:lang="fr" val="Autoformation sans tutorat" />
    </entry>
    <entry>
      <key val="96127" />
      <value xml:lang="fr" val="Chantier école" />
    </entry>
    <entry>
      <key val="96142" />
      <value xml:lang="fr" val="En alternance" />
    </entry>
    <entry>
      <key val="96129" />
      <value xml:lang="fr" val="FOAD" />
    </entry>
    <entry>
      <key val="96133" />
      <value xml:lang="fr" val="FOAD avec tutorat asynchrone" />
    </entry>
    <entry>
      <key val="96130" />
      <value xml:lang="fr" val="FOAD avec tutorat synchrone" />
    </entry>
    <entry>
      <key val="96131" />
      <value xml:lang="fr" val="FOAD sans tutorat" />
    </entry>
    <entry>
      <key val="96128" />
      <value xml:lang="fr" val="Formation à distance" />
    </entry>
    <entry>
      <key val="96134" />
      <value xml:lang="fr" val="Formation action" />
    </entry>
    <entry>
      <key val="96147" />
      <value xml:lang="fr" val="Formation en situation de travail" />
    </entry>
    <entry>
      <key val="96132" />
      <value xml:lang="fr" val="Pédagogie adaptée aux handicapés" />
    </entry>
    <entry>
      <key val="96149" />
      <value xml:lang="fr" val="Séjour à l'étranger" />
    </entry>
    <entry>
      <key val="96410" />
      <value xml:lang="fr" val="Périodes de formation" />
    </entry>
    <entry>
      <key val="96414" />
      <value xml:lang="fr" val="Cours de jour" />
    </entry>
    <entry>
      <key val="96411" />
      <value xml:lang="fr" val="Cours du soir" />
    </entry>
    <entry>
      <key val="96412" />
      <value xml:lang="fr" val="Cours le week end" />
    </entry>
    <entry>
      <key val="96413" />
      <value xml:lang="fr" val="Hors temps de travail" />
    </entry>

  <property name="version" value="V10" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/sources/regions-france-2007-insee.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-regions-france">
<fullname xml:lang="fr">Régions françaises (2007)</fullname>
<doc xml:lang="fr">Régions françaises version 2007 (source : INSEE)</doc>
<entry>
  <key val="01" />
  <value val="Guadeloupe" />
  <property name="insee:cheflieu" value="97105" />
</entry>
<entry>
  <key val="02" />
  <value val="Martinique" />
  <property name="insee:cheflieu" value="97209" />
</entry>
<entry>
  <key val="03" />
  <value val="Guyane" />
  <property name="insee:cheflieu" value="97302" />
</entry>
<entry>
  <key val="04" />
  <value val="La Réunion" />
  <property name="insee:cheflieu" value="97411" />
</entry>
<entry>
  <key val="11" />
  <value val="Île-de-France" />
  <property name="insee:cheflieu" value="75056" />
</entry>
<entry>
  <key val="21" />
  <value val="Champagne-Ardenne" />
  <property name="insee:cheflieu" value="51108" />
</entry>
<entry>
  <key val="22" />
  <value val="Picardie" />
  <property name="insee:cheflieu" value="80021" />
</entry>
<entry>
  <key val="23" />
  <value val="Haute-Normandie" />
  <property name="insee:cheflieu" value="76540" />
</entry>
<entry>
  <key val="24" />
  <value val="Centre" />
  <property name="insee:cheflieu" value="45234" />
</entry>
<entry>
  <key val="25" />
  <value val="Basse-Normandie" />
  <property name="insee:cheflieu" value="14118" />
</entry>
<entry>
  <key val="26" />
  <value val="Bourgogne" />
  <property name="insee:cheflieu" value="21231" />
</entry>
<entry>
  <key val="31" />
  <value val="Nord-Pas-de-Calais" />
  <property name="insee:cheflieu" value="59350" />
</entry>
<entry>
  <key val="41" />
  <value val="Lorraine" />
  <property name="insee:cheflieu" value="57463" />
</entry>
<entry>
  <key val="42" />
  <value val="Alsace" />
  <property name="insee:cheflieu" value="67482" />
</entry>
<entry>
  <key val="43" />
  <value val="Franche-Comté" />
  <property name="insee:cheflieu" value="25056" />
</entry>
<entry>
  <key val="52" />
  <value val="Pays de la Loire" />
  <property name="insee:cheflieu" value="44109" />
</entry>
<entry>
  <key val="53" />
  <value val="Bretagne" />
  <property name="insee:cheflieu" value="35238" />
</entry>
<entry>
  <key val="54" />
  <value val="Poitou-Charentes" />
  <property name="insee:cheflieu" value="86194" />
</entry>
<entry>
  <key val="72" />
  <value val="Aquitaine" />
  <property name="insee:cheflieu" value="33063" />
</entry>
<entry>
  <key val="73" />
  <value val="Midi-Pyrénées" />
  <property name="insee:cheflieu" value="31555" />
</entry>
<entry>
  <key val="74" />
  <value val="Limousin" />
  <property name="insee:cheflieu" value="87085" />
</entry>
<entry>
  <key val="82" />
  <value val="Rhône-Alpes" />
  <property name="insee:cheflieu" value="69123" />
</entry>
<entry>
  <key val="83" />
  <value val="Auvergne" />
  <property name="insee:cheflieu" value="63113" />
</entry>
<entry>
  <key val="91" />
  <value val="Languedoc-Roussillon" />
  <property name="insee:cheflieu" value="34172" />
</entry>
<entry>
  <key val="93" />
  <value val="Provence-Alpes-Côte d'Azur" />
  <property name="insee:cheflieu" value="13055" />
</entry>
<entry>
  <key val="94" />
  <value val="Corse" />
  <property name="insee:cheflieu" value="2A004" />
</entry>
<property name="version" value="2007" />
</dict>

=== lheo/lheo-schema/definition/dict-modalites-es.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-modalites-es">
  <fullname xml:lang="fr">Modalités d'entrées/sorties</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="0"/>
      <value xml:lang="fr" val="entrées/sorties à dates fixes"/>
    </entry>
    <entry>
      <key val="1"/>
      <value xml:lang="fr" val="entrées/sorties permanentes"/>
    </entry>
  <property name="version" value="V1" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/dict-etat-recrutement.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-etat-recrutement">
  <fullname xml:lang="fr">Etat du recrutement</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="1"/>
      <value xml:lang="fr" val="ouvert"/>
    </entry>
    <entry>
      <key val="2"/>
      <value xml:lang="fr" val="fermÃ©"/>
    </entry>
    <entry>
      <key val="3"/>
      <value xml:lang="fr" val="suspendu"/>
    </entry>
  <property name="version" value="V1" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/dict-AIS.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-AIS">
  <fullname xml:lang="fr">Objectif général de formation</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="1"/>
      <value xml:lang="fr" val="Code(s) obsolète(s)"/>
    </entry>
    <entry>
      <key val="6"/>
      <value xml:lang="fr" val="Certification"/>
    </entry>
    <entry>
      <key val="7"/>
      <value xml:lang="fr" val="Professionnalisation"/>
    </entry>
    <entry>
      <key val="8"/>
      <value xml:lang="fr" val="Préparation à la qualification"/>
    </entry>
    <entry>
      <key val="5"/>
      <value xml:lang="fr" val="Remise à niveau, maîtrise des savoirs de base, initiation"/>
    </entry>
    <entry>
      <key val="9"/>
      <value xml:lang="fr" val="(Re)mobilisation, aide à l'élaboration de projet professionnel"/>
    </entry>
    <entry>
      <key val="2"/>
      <value xml:lang="fr" val="Perfectionnement, élargissement des compétences"/>
    </entry>
    <entry>
      <key val="4"/>
      <value xml:lang="fr" val="Création d'entreprise"/>
    </entry>
  <property name="version" value="V1" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/dict-niveaux.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-niveaux">
  <fullname xml:lang="fr">Niveaux</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="0" />
      <value xml:lang="fr" val="information non communiquée" />
    </entry>
    <entry>
      <key val="1" />
      <value xml:lang="fr" val="sans niveau spécifique" />
    </entry>
    <entry>
      <key val="2" />
      <value xml:lang="fr" val="niveau VI (illettrisme, analphabétisme)" />
    </entry>
    <entry>
      <key val="3" />
      <value xml:lang="fr" val="niveau V bis (préqualification)" />
    </entry>
    <entry>
      <key val="4" />
      <value xml:lang="fr" val="niveau V (CAP, BEP, CFPA du premier degré)" />
    </entry>
    <entry>
      <key val="5" />
      <value xml:lang="fr" val="niveau IV (BP, BT, baccalauréat professionnel ou technologique)" />
    </entry>
    <entry>
      <key val="6" />
      <value xml:lang="fr" val="niveau III (BTS, DUT)" />
    </entry>
    <entry>
      <key val="7" />
      <value xml:lang="fr" val="niveau II (licence ou maîtrise universitaire)" />
    </entry>
    <entry>
      <key val="8" />
      <value xml:lang="fr" val="niveau I (supérieur à la maîtrise)" />
    </entry>
  <property name="version" value="V1" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/dict-public-vise-formacode-V10.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-public-vise-formacode-V10">
  <fullname xml:lang="fr">Public visé formacode V10</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="80001" />
      <value xml:lang="fr" val="Public sans emploi" />
    </entry>
    <entry>
      <key val="80003" />
      <value xml:lang="fr" val="Demandeur d'emploi plus de 26 ans" />
    </entry>
    <entry>
      <key val="80004" />
      <value xml:lang="fr" val="Cadre demandeur d'emploi" />
    </entry>
    <entry>
      <key val="80005" />
      <value xml:lang="fr" val="Bénéficiaire du revenu de solidarité active" />
    </entry>
    <entry>
      <key val="80006" />
      <value xml:lang="fr" val="Demandeur d'emploi" />
    </entry>
    <entry>
      <key val="80007" />
      <value xml:lang="fr" val="Demandeur d'emploi longue durée" />
    </entry>
    <entry>
      <key val="80008" />
      <value xml:lang="fr" val="Licencié pour motif économique" />
    </entry>
    <entry>
      <key val="80009" />
      <value xml:lang="fr" val="Demandeur d'emploi moins de 26 ans" />
    </entry>
    <entry>
      <key val="80010" />
      <value xml:lang="fr" val="Militaire en reconversion" />
    </entry>
    <entry>
      <key val="80015" />
      <value xml:lang="fr" val="Bénéficiaire allocation solidarité spécifique" />
    </entry>
    <entry>
      <key val="80019" />
      <value xml:lang="fr" val="Bénéficiaire allocation retour à l'emploi" />
    </entry>
    <entry>
      <key val="80023" />
      <value xml:lang="fr" val="Demandeur d'emploi dans le cadre du CIF" />
    </entry>
    <entry>
      <key val="80026" />
      <value xml:lang="fr" val="Demandeur d'emploi dans le cadre du DIF" />
    </entry>
    <entry>
      <key val="80098" />
      <value xml:lang="fr" val="Jeune (dans le cadre du plan jeune)" />
    </entry>
    <entry>
      <key val="81013" />
      <value xml:lang="fr" val="Public sous main de justice" />
    </entry>
    <entry>
      <key val="81014" />
      <value xml:lang="fr" val="Élu" />
    </entry>
    <entry>
      <key val="81018" />
      <value xml:lang="fr" val="Femme" />
    </entry>
    <entry>
      <key val="81019" />
      <value xml:lang="fr" val="Public en situation d'illettrisme" />
    </entry>
    <entry>
      <key val="81020" />
      <value xml:lang="fr" val="Handicapé" />
    </entry>
    <entry>
      <key val="81021" />
      <value xml:lang="fr" val="Public analphabète" />
    </entry>
    <entry>
      <key val="81022" />
      <value xml:lang="fr" val="Immigré" />
    </entry>
    <entry>
      <key val="81024" />
      <value xml:lang="fr" val="Jeune" />
    </entry>
    <entry>
      <key val="81042" />
      <value xml:lang="fr" val="Réfugié" />
    </entry>
    <entry>
      <key val="81050" />
      <value xml:lang="fr" val="Particulier, individuel" />
    </entry>
    <entry>
      <key val="81060" />
      <value xml:lang="fr" val="Conjoint collaborateur d'artisan" />
    </entry>
    <entry>
      <key val="81061" />
      <value xml:lang="fr" val="Public de la formation initiale" />
    </entry>
    <entry>
      <key val="81062" />
      <value xml:lang="fr" val="Conjoint collaborateur d'exploitant agricole" />
    </entry>
    <entry>
      <key val="81069" />
      <value xml:lang="fr" val="Bénévole" />
    </entry>
    <entry>
      <key val="81099" />
      <value xml:lang="fr" val="Autre public" />
    </entry>
    <entry>
      <key val="82004" />
      <value xml:lang="fr" val="Artisan" />
    </entry>
    <entry>
      <key val="82009" />
      <value xml:lang="fr" val="Commerçant" />
    </entry>
    <entry>
      <key val="82016" />
      <value xml:lang="fr" val="Formateur, enseignant" />
    </entry>
    <entry>
      <key val="82017" />
      <value xml:lang="fr" val="Exploitant agricole, salarié agricole" />
    </entry>
    <entry>
      <key val="82027" />
      <value xml:lang="fr" val="Public dans le cadre du contrat d'apprentissage" />
    </entry>
    <entry>
      <key val="82029" />
      <value xml:lang="fr" val="Public dans le cadre du contrat de professionnalisation" />
    </entry>
    <entry>
      <key val="82038" />
      <value xml:lang="fr" val="Profession libérale" />
    </entry>
    <entry>
      <key val="82043" />
      <value xml:lang="fr" val="Représentant du personnel" />
    </entry>
    <entry>
      <key val="82044" />
      <value xml:lang="fr" val="Salarié" />
    </entry>
    <entry>
      <key val="82045" />
      <value xml:lang="fr" val="Salarié en reconversion" />
    </entry>
    <entry>
      <key val="82046" />
      <value xml:lang="fr" val="Salarié de l'artisanat" />
    </entry>
    <entry>
      <key val="82047" />
      <value xml:lang="fr" val="Salarié en contrat aidé" />
    </entry>
    <entry>
      <key val="82055" />
      <value xml:lang="fr" val="Agent de la fonction publique" />
    </entry>
    <entry>
      <key val="82058" />
      <value xml:lang="fr" val="Public en emploi" />
    </entry>
    <entry>
      <key val="82065" />
      <value xml:lang="fr" val="Salarié dans le cadre du plan de formation" />
    </entry>
    <entry>
      <key val="82066" />
      <value xml:lang="fr" val="Salarié dans le cadre du CIF" />
    </entry>
    <entry>
      <key val="82067" />
      <value xml:lang="fr" val="Membre du CHSCT" />
    </entry>
    <entry>
      <key val="82068" />
      <value xml:lang="fr" val="Membre du CE" />
    </entry>
    <entry>
      <key val="82070" />
      <value xml:lang="fr" val="Agent de la fonction publique d'Etat" />
    </entry>
    <entry>
      <key val="82071" />
      <value xml:lang="fr" val="Agent de la fonction publique hospitalière" />
    </entry>
    <entry>
      <key val="82072" />
      <value xml:lang="fr" val="Salarié dans le cadre du DIF" />
    </entry>
    <entry>
      <key val="82073" />
      <value xml:lang="fr" val="Salarié en période de professionnalisation" />
    </entry>
    <entry>
      <key val="82074" />
      <value xml:lang="fr" val="Agent de la fonction publique territoriale" />
    </entry>
    <entry>
      <key val="83056" />
      <value xml:lang="fr" val="Tout public" />
    </entry>
  <property name="version" value="V10" />
  <property name="url" value="" />
</dict>

=== lheo/lheo-schema/definition/dict-FOAD.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE dict SYSTEM "gml.dtd">
<dict xmlns="http://www.gelaba.org/gml/1.1" name="dict-FOAD">
  <fullname xml:lang="fr">FOAD</fullname>
  <doc xml:lang="fr">
  </doc>
    <entry>
      <key val="0" />
      <value xml:lang="fr" val="formation entièrement présentielle" />
    </entry>
    <entry>
      <key val="1" />
      <value xml:lang="fr" val="formation mixte" />
    </entry>
    <entry>
      <key val="2" />
      <value xml:lang="fr" val="formation entièrement à distance" />
    </entry>
  <property name="version" value="V1" />
  <property name="url" value="" />
</dict>
